/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany;

import java.awt.event.KeyEvent;

/**
 *
 * @author luizviniciusruoso
 */
public class Tabuleiro extends javax.swing.JFrame {

    /**
     * Creates new form Tabuleiro
     */
    public Tabuleiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pos1 = new javax.swing.JPanel();
        pos2 = new javax.swing.JPanel();
        pos3 = new javax.swing.JPanel();
        pos4 = new javax.swing.JPanel();
        pos5 = new javax.swing.JPanel();
        pos6 = new javax.swing.JPanel();
        pos7 = new javax.swing.JPanel();
        pos8 = new javax.swing.JPanel();
        pos9 = new javax.swing.JPanel();
        pos10 = new javax.swing.JPanel();
        pos11 = new javax.swing.JPanel();
        pos12 = new javax.swing.JPanel();
        pos13 = new javax.swing.JPanel();
        pos14 = new javax.swing.JPanel();
        pos15 = new javax.swing.JPanel();
        pos16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(142, 176, 230));
        setForeground(new java.awt.Color(175, 195, 226));
        setPreferredSize(new java.awt.Dimension(425, 440));

        pos1.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos1Layout = new javax.swing.GroupLayout(pos1);
        pos1.setLayout(pos1Layout);
        pos1Layout.setHorizontalGroup(
            pos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos1Layout.setVerticalGroup(
            pos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pos2.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos2Layout = new javax.swing.GroupLayout(pos2);
        pos2.setLayout(pos2Layout);
        pos2Layout.setHorizontalGroup(
            pos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        pos2Layout.setVerticalGroup(
            pos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pos3.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos3Layout = new javax.swing.GroupLayout(pos3);
        pos3.setLayout(pos3Layout);
        pos3Layout.setHorizontalGroup(
            pos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        pos3Layout.setVerticalGroup(
            pos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pos4.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos4Layout = new javax.swing.GroupLayout(pos4);
        pos4.setLayout(pos4Layout);
        pos4Layout.setHorizontalGroup(
            pos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        pos4Layout.setVerticalGroup(
            pos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pos5.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos5Layout = new javax.swing.GroupLayout(pos5);
        pos5.setLayout(pos5Layout);
        pos5Layout.setHorizontalGroup(
            pos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos5Layout.setVerticalGroup(
            pos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pos6.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos6Layout = new javax.swing.GroupLayout(pos6);
        pos6.setLayout(pos6Layout);
        pos6Layout.setHorizontalGroup(
            pos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos6Layout.setVerticalGroup(
            pos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pos7.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos7Layout = new javax.swing.GroupLayout(pos7);
        pos7.setLayout(pos7Layout);
        pos7Layout.setHorizontalGroup(
            pos7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos7Layout.setVerticalGroup(
            pos7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pos8.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos8Layout = new javax.swing.GroupLayout(pos8);
        pos8.setLayout(pos8Layout);
        pos8Layout.setHorizontalGroup(
            pos8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos8Layout.setVerticalGroup(
            pos8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pos9.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos9Layout = new javax.swing.GroupLayout(pos9);
        pos9.setLayout(pos9Layout);
        pos9Layout.setHorizontalGroup(
            pos9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos9Layout.setVerticalGroup(
            pos9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pos10.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos10Layout = new javax.swing.GroupLayout(pos10);
        pos10.setLayout(pos10Layout);
        pos10Layout.setHorizontalGroup(
            pos10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos10Layout.setVerticalGroup(
            pos10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pos11.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos11Layout = new javax.swing.GroupLayout(pos11);
        pos11.setLayout(pos11Layout);
        pos11Layout.setHorizontalGroup(
            pos11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos11Layout.setVerticalGroup(
            pos11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pos12.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos12Layout = new javax.swing.GroupLayout(pos12);
        pos12.setLayout(pos12Layout);
        pos12Layout.setHorizontalGroup(
            pos12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos12Layout.setVerticalGroup(
            pos12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pos13.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos13Layout = new javax.swing.GroupLayout(pos13);
        pos13.setLayout(pos13Layout);
        pos13Layout.setHorizontalGroup(
            pos13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        pos13Layout.setVerticalGroup(
            pos13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pos14.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos14Layout = new javax.swing.GroupLayout(pos14);
        pos14.setLayout(pos14Layout);
        pos14Layout.setHorizontalGroup(
            pos14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos14Layout.setVerticalGroup(
            pos14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pos15.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos15Layout = new javax.swing.GroupLayout(pos15);
        pos15.setLayout(pos15Layout);
        pos15Layout.setHorizontalGroup(
            pos15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos15Layout.setVerticalGroup(
            pos15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pos16.setBackground(new java.awt.Color(175, 195, 226));

        javax.swing.GroupLayout pos16Layout = new javax.swing.GroupLayout(pos16);
        pos16.setLayout(pos16Layout);
        pos16Layout.setHorizontalGroup(
            pos16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pos16Layout.setVerticalGroup(
            pos16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pos13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pos4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pos4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pos5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pos9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pos13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Tabuleiro().setVisible(true);
            }
        });
    }
    
    
    public void keyPressed(KeyEvent e) {

    int key = e.getKeyCode();



    if (key == KeyEvent.VK_DOWN) {
        System.out.println("Baixo");
    }
}
      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pos1;
    private javax.swing.JPanel pos10;
    private javax.swing.JPanel pos11;
    private javax.swing.JPanel pos12;
    private javax.swing.JPanel pos13;
    private javax.swing.JPanel pos14;
    private javax.swing.JPanel pos15;
    private javax.swing.JPanel pos16;
    private javax.swing.JPanel pos2;
    private javax.swing.JPanel pos3;
    private javax.swing.JPanel pos4;
    private javax.swing.JPanel pos5;
    private javax.swing.JPanel pos6;
    private javax.swing.JPanel pos7;
    private javax.swing.JPanel pos8;
    private javax.swing.JPanel pos9;
    // End of variables declaration//GEN-END:variables
}

